random_crop:
  crop_size: 224
color_jitter:
  jitter_brightness: 0.3
  jitter_contrast: 0.3
  jitter_saturation: 0.3
  jitter_hue: 0.1
random_horizontal_flip:
  prob: 0.5
random_rotation:
  degrees: 15