_target_: src.core.builder.XModel
task: ${training.task.type}
type: weight_posture

Model:
  input_channel: 4
  Backbone:
    # [from, number, module, args]
    [ 
      [-1, 1, VGGBlock, [64, 3]],    # 0 
      [-1, 1, VGGBlock, [64, 3]],    # 0 
      [-1, 1, VGGMaxPoolBlock, [64]],  # 1 

      [-1, 1, VGGBlock, [128, 3]], # 2 
      [-1, 1, VGGBlock, [128, 3]], # 2 
      [-1, 1, VGGMaxPoolBlock, [128]], # 3 

      [-1, 1, VGGBlock, [256, 3]], # 4 
      [-1, 3, VGGBlock, [256, 3]], # 4  
      [-1, 1, VGGMaxPoolBlock, [256]], # 5 

      [-1, 1, VGGBlock, [512, 3]], # 6 
      [-1, 3, VGGBlock, [512, 3]], # 6
      [-1, 1, VGGMaxPoolBlock, [512]], # 7 

      [-1, 1, VGGBlock, [512, 3]], # 8 
      [-1, 3, VGGBlock, [512, 3]], # 8 
      [-1, 1, VGGMaxPoolBlock, [512]], # 9 
    ]

  Head:
    [
      [-1, 1, CoupleHead,[2048]], # Detect(P3, P4, P5)27
    ]

  weights: ""
