parameter:
  epochs: 100
  batch_size: 256
  num_workers: 10
  seed: 20
  device: cuda
  use_amp: true  # 是否使用自动混合精度


task:
  type: weight_posture
  loss:
    _target_: src.core.loss.PWAPLoss

metrics:
  regression:
    - mae
    - rmse
    - r2
    - mape
  classification:
    - accuracy
    - f1