# 引用默认配置
defaults:
  - exp32
  - _self_  # 确保当前配置覆盖默认值

testing:
  checkpoint: "/home/xpg/mlartifacts/941656278979793273/0ecdca9005d247bd9fa4df38a39b8570/artifacts/best_model.pth"
  metrics:
    regression:
      - mae
      - rmse
      - r2
      - mape
    classification:
      - accuracy
      - f1
