# 引用默认配置
defaults:
  - exp31
  - _self_  # 确保当前配置覆盖默认值

testing:
  checkpoint: "/home/xpg/mlartifacts/941656278979793273/d5c8290ea1be4155b1c661d0fa63dc83/artifacts/best_model.pth"
  metrics:
    regression:
      - mae
      - rmse
      - r2
      - mape
    classification:
      - accuracy
      - f1
