# 引用默认配置
defaults:
  - best
  - _self_  # 确保当前配置覆盖默认值

testing:
  checkpoint: weights/wpmnet_best_model.pth
  metrics:
    regression:
      - mae
      - rmse
      - r2
      - mape
    classification:
      - accuracy
      - f1
